# Generated by Django 3.0 on 2020-02-22 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=40)),
                ('doctor_address', models.TextField()),
                ('doctor_contact', models.IntegerField(max_length=10)),
                ('doctor_age', models.IntegerField(max_length=3)),
                ('doctor_ID', models.IntegerField(unique=True)),
                ('doctor_join_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=40)),
                ('patient_address', models.TextField()),
                ('patient_contact', models.IntegerField(max_length=10)),
                ('pateint_age', models.IntegerField(max_length=3)),
                ('patient_ID', models.IntegerField(unique=True)),
                ('patient_registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(max_length=3)),
                ('disease', models.TextField()),
                ('dignosis', models.TextField()),
                ('suggestion', models.TextField()),
                ('Fees', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_data.Doctor')),
                ('paitent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_data.Patient')),
            ],
        ),
    ]
