# Generated by Django 3.0 on 2020-02-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pateint_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
