# Generated by Django 3.0 on 2020-02-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0002_auto_20200222_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_age',
            field=models.IntegerField(),
        ),
    ]
