# Generated by Django 3.0 on 2020-02-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0003_auto_20200222_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='dignosis',
            new_name='diagnosis',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='Fees',
            new_name='fees',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_contact',
            field=models.CharField(max_length=10),
        ),
    ]
