# Generated by Django 3.0 on 2020-02-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0004_auto_20200222_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
