# Generated by Django 3.0 on 2020-02-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0005_record_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='paitent',
            new_name='patient',
        ),
    ]
