# Generated by Django 3.0 on 2020-02-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0006_auto_20200222_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='pateint_age',
            new_name='patient_age',
        ),
    ]
