# Generated by Django 3.0 on 2020-02-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0007_auto_20200223_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_city',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_city',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
