# Generated by Django 3.0 on 2020-02-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0009_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='date_applied',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
