# Generated by Django 3.0 on 2020-03-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0012_auto_20200226_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='status',
            field=models.CharField(choices=[('Checked', 'Checked'), ('Unchecked', 'Unchecked')], default='Unchecked', max_length=10),
        ),
    ]
