# Generated by Django 3.0 on 2020-03-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0013_career_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.CharField(choices=[('Checked', 'Checked'), ('Unchecked', 'Unchecked')], default='Unchecked', max_length=10),
        ),
    ]
