# Generated by Django 3.0 on 2020-03-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AradhyaGallery', '0002_remove_gallery_g_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='g_image',
            field=models.ImageField(default='/media/default.png', upload_to='images'),
        ),
    ]
