# Generated by Django 3.0 on 2020-03-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AradhyaGallery', '0003_auto_20200301_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='g_image',
            field=models.ImageField(default='/default.png', upload_to='images'),
        ),
    ]
